import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="bg-slate-900 text-slate-100 overflow-x-hidden" lang="en">
      <body
      >
        <Header/>
        {children}
        <div className="h-[500vh]"></div>
      </body>
    </html>
  );
}
